version: '3'

services:
  ################################
  #   Setup react js container
  ################################
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ExamSim_app
    ports:
      - 9000:9000
  ################################
  #   Setup react js container
  ################################
  gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
    container_name: ExamSim_gui
    ports:
      - 3000:3000
    volumes:
#      - ./gui:/gui
      - /gui/node_modules
  ################################
  #   Setup nginx load balancer
  ################################
  nginx:
    image: nginx:latest
    ports:
      - 3080:3000
    environment:
      - TARGET_DOMAIN=localhost
  ################################
  #   Setup mongo db
  ################################
  mongo:
    container_name: ExamSim_mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "mongoadmin"
      MONGO_INITDB_DATABASE: "examsim"
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro