version: '3'

networks:
  examsim_network:
    external: false

services:
  ################################
  #   Setup react js container
  ################################
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: examsim_app
    networks:
      - examsim_network
    ports:
      - 9000:9000
  ################################
  #   Setup react js container
  ################################
  gui:
    build:
      context: ./gui
      dockerfile: Dockerfile
    stdin_open: true # docker run -it
    tty: true
    container_name: examsim_gui
    networks:
      - examsim_network
    ports:
      - 3000:3000
#    volumes:
#      - ./gui:/gui
#      - /gui/node_modules
  ################################
  #   Setup nginx load balancer
  ################################
#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    container_name: examsim_proxy
#    networks:
#      - examsim_network
#    ports:
#      - 3080:3080
  ################################
  #   Setup mongo db
  ################################
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
      MONGO_INITDB_ROOT_PASSWORD: "mongoadmin"
      MONGO_INITDB_DATABASE: "examsim"
    ports:
      - 27017:27017
    container_name: examsim_mongo
    networks:
      - examsim_network
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

